### ISSUE TITLE
Username change

### ISSUE THREAD

**Issue by Elioz** [GotoFinal/AutoIn#26]
Hello,

What happend if premium user has changed username and not able to connect again?

Thanks!

**Comment by TheMolkaPL** [comment]
His UUID is not changed so he can connect normally.

**Comment by GotoFinal** [comment]
If you have FixedUUID set to true, then you have problem, because UUID of player will change.
But if not (by default it is false) they everything should work, you can have only problems with other plugins, like AuthMe can block him because it may think that it's second account for that IP.
PS: please, use spigot page to ask questions.
